# Generated by Django 5.1.6 on 2025-02-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
