# Generated by Django 5.1.6 on 2025-03-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mskr', '0002_profile_date_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followers',
            new_name='follows',
        ),
    ]
