# Generated by Django 5.1.6 on 2025-03-10 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mskr', '0004_meep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meep',
            old_name='create',
            new_name='created_at',
        ),
    ]
