# Generated by Django 5.1.6 on 2025-03-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mskr', '0007_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
