# Generated by Django 5.1.6 on 2025-03-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskr', '0009_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
