# Generated by Django 5.1.6 on 2025-03-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskr', '0010_profile_prof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
