# Generated by Django 5.1.6 on 2025-03-19 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mskr', '0011_alter_profile_prof_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
