# Generated by Django 5.1.6 on 2025-03-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mskr', '0013_meep_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meep',
            name='title',
        ),
    ]
