# Generated by Django 5.1.6 on 2025-03-21 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mskr', '0015_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
